# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  
name: CI

on:
  push:
    branches:
    - main
    - release/*

jobs:
  firebase-deploy:

    runs-on: ubuntu-latest

    steps:
     - uses: actions/checkout@main
     - uses: actions/setup-node@main
       with:
        node-version: <15.x<
     - run: npm install
     - run: npm run build --prod
     - uses: w9jds/firebase-action@main
       with:
         args: deploy --only hosting
       env:
         FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}


